package org.example.calendar.fileops;/* Generated By:JavaCC: Do not edit this line. MyDSLParserConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface MyDSLParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int EVENT = 1;
  /** RegularExpression Id. */
  int PLUGIN = 2;
  /** RegularExpression Id. */
  int SCRIPT = 3;
  /** RegularExpression Id. */
  int DATE = 4;
  /** RegularExpression Id. */
  int TIME = 5;
  /** RegularExpression Id. */
  int DURATION = 6;
  /** RegularExpression Id. */
  int ALL_DAY = 7;
  /** RegularExpression Id. */
  int IDENTIFIER = 8;
  /** RegularExpression Id. */
  int STRING = 9;
  /** RegularExpression Id. */
  int COLON = 10;
  /** RegularExpression Id. */
  int COMMA = 11;
  /** RegularExpression Id. */
  int LBRACE = 12;
  /** RegularExpression Id. */
  int RBRACE = 13;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"event\"",
    "\"plugin\"",
    "\"script\"",
    "\"([0-9]{4}-[0-9]{2}-[0-9]{2})\"",
    "\"([0-9]{2}:[0-9]{2}:[0-9]{2})\"",
    "\"([0-9]+)\"",
    "\"all-day\"",
    "<IDENTIFIER>",
    "<STRING>",
    "\":\"",
    "\",\"",
    "\"{\"",
    "\"}\"",
  };

}
