/* Generated By:JavaCC: Do not edit this line. MainParserConstants.java */
package org.example.calendar.javaccparser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface MainParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int EVENT = 1;
  /** RegularExpression Id. */
  int PLUGIN = 2;
  /** RegularExpression Id. */
  int SCRIPT = 3;
  /** RegularExpression Id. */
  int DATE = 4;
  /** RegularExpression Id. */
  int TIME = 5;
  /** RegularExpression Id. */
  int DURATION = 6;
  /** RegularExpression Id. */
  int ALL_DAY = 7;
  /** RegularExpression Id. */
  int STRING = 8;
  /** RegularExpression Id. */
  int CLASS_NAME = 9;
  /** RegularExpression Id. */
  int JAVA_ID = 10;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"event \"",
    "\"plugin\"",
    "\"script\"",
    "<DATE>",
    "<TIME>",
    "<DURATION>",
    "\"all-day\"",
    "<STRING>",
    "<CLASS_NAME>",
    "<JAVA_ID>",
    "\"{\"",
    "\"}\"",
    "\":\"",
    "\",\"",
    "\" \"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\t\"",
  };

}
